# Generated by Django 4.2 on 2023-04-16 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_brand_alter_car_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='model',
            new_name='name',
        ),
    ]
